### PR TITLE
Set properties for ResteasyClientBuilder methods with multiple params

### LINKED ISSUE #18: Unable to set multiple properties on ResteasyClientBuilder
Due to the way `RestEasyClientBuilder` is written there are a number of properties that cannot be set via `RestClientBuilder` as they take two values: `long` and `TimeUnit`. These include:
* `connectionCheckoutTimeout`
* `establishConnectionTimeout`
* `connectionTTL`
* `socketTimeout`

Although not perfect, it could be altered to check for these types and allow setting, implying milliseconds only:

```
    private static final Set<String> TIMEUNIT_PROPERTY = new HashSet<>(asList(
            "connectionCheckoutTimeout",
            "establishConnectionTimeout",
            "connectionTTL",
            "socketTimeout"
    ));

    ...

    @Override
    public RestClientBuilder property(String name, Object value) {
        if (name.startsWith(RESTEASY_PROPERTY_PREFIX)) {
            // Allows to configure some of the ResteasyClientBuilder delegate properties
            String builderMethodName = name.substring(RESTEASY_PROPERTY_PREFIX.length());
            try {
                if (TIMEUNIT_PROPERTY.contains(name)) {
                    Method builderMethod = ResteasyClientBuilder.class.getMethod(builderMethodName, unwrapPrimitiveType(value), TimeUnit.class);
                    builderMethod.invoke(builderDelegate, value, TimeUnit.MILLISECONDS);
                } else {
                    Method builderMethod = ResteasyClientBuilder.class.getMethod(builderMethodName, unwrapPrimitiveType(value));
                    builderMethod.invoke(builderDelegate, value);		
                }
            } catch (NoSuchMethodException e) {
                LOGGER.warnf("ResteasyClientBuilder method %s not found", builderMethodName);
            } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
                LOGGER.errorf(e, "Unable to invoke ResteasyClientBuilder method %s", builderMethodName);
            }
        }
        this.builderDelegate.property(name, value);
        return this;
    }
```

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #18

### CODE REVIEW

**Comment by mkouba** [comment]
@dansiviter Pls review - I've tried to make the solution more robust so that it's possible to pass multiple params using `List<>`.

File: implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java [hunk 1]
```diff
@@ -160,20 +156,17 @@ public RestClientBuilder executorService(ExecutorService executor) {
...
 
-        client = resteasyClientBuilder
-                .build();
+        client = resteasyClientBuilder.build();
 
-        actualClient = client.target(baseURI)
-                .proxyBuilder(aClass)
-                .classloader(classLoader)
-                .defaultConsumes(MediaType.APPLICATION_OCTET_STREAM)
+        actualClient = client.target(baseURI).proxyBuilder(aClass).classloader(classLoader).defaultConsumes(MediaType.APPLICATION_OCTET_STREAM)
```
Comment (michalszynkiewicz) [inline implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java]: formatting :(

**Comment by michalszynkiewicz** [comment]
this commit makes code formatting worse but other than that looks good to me

File: implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java (hunk 1 above)
Comment (mkouba) [reply implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java]: Ah, I'm sorry. I accidentally formatted the whole file with WildFly defaults. I'll revert some of the changes ;-)

File: implementation/src/test/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver [hunk 2]
```diff
@@ -0,0 +1 @@
+io.smallrye.restclient.BuilderResolver
```
Comment (michalszynkiewicz) [inline implementation/src/test/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver]: why was that not needed before and is needed now?

File: implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java [hunk 3]
```diff
@@ -272,32 +270,33 @@ public Configuration getConfiguration() {
     @Override
     public RestClientBuilder property(String name, Object value) {
         if (name.startsWith(RESTEASY_PROPERTY_PREFIX)) {
-            // Allows to configure some of the ResteasyClientBuilder delegate properties
+            // Makes it possible to configure some of the ResteasyClientBuilder delegate properties
             String builderMethodName = name.substring(RESTEASY_PROPERTY_PREFIX.length());
+            Method builderMethod = Arrays.stream(ResteasyClientBuilder.class.getMethods())
```
Comment (michalszynkiewicz) [inline implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java]: it's more readable with `findFirst` and `orElse` in their own lines ;)

File: implementation/src/test/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver (hunk 2 above)
Comment (mkouba) [reply implementation/src/test/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver]: Because of `RestClientBuilderResteasyPropertiesTest` unit test.

File: implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java (hunk 3 above)
Comment (mkouba) [reply implementation/src/main/java/io/smallrye/restclient/RestClientBuilderImpl.java]: Is it better now? ;-)
